common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns=[
    path('', views.common_index, name='common_index'),
    path('signin', views.common_signin, name='common_signin'),
    path('signup', views.common_signup, name='common_signup'),
    path('faqs', views.common_faqs, name='common_faqs'),
    path('contact', views.common_contact, name='common_contact'),
    path('home', views.customer_home, name='customer_home'), 

]

netflixerp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include ('common.urls')),
]

common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.

def common_index(request):
    return render(request,'common_templates/index.html')

def common_contact(request):
    return render(request,'common_templates/contact.html')

def common_faqs(request):
    return render(request,'common_templates/faqs.html')

def common_signin(request):
    return render(request,'common_templates/signin.html')

def common_signup(request):
    return render(request,'common_templates/signup.html')

def customer_home(request):
    return render(request,'common_templates/home.html')

common/templates/common_templates/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <link rel="stylesheet" href="{% static 'css/contactstyle.css' %} ">
    
</head>
<body>
    <div class="container" >
        
        <div class="header">
            <div class="logo">
                <a href="{% url 'common:common_index' %}">
                <img src="static/images/logo2.png" height="100%" width="70%" no-repeat >
                </a>
            </div>
            <div class="language">
                <form method="get">
                <select name="language" multiple size="1">
                    <!--size here used to show size of list displayed-->
                    <option selected>English</option>
                    <option>Hindi</option>
                    <option>French</option>
                    <option>German</option>
                    <option>Malayalam</option>
                </select>
                </form>
            </div>
            <div class="signin">
                <a href="{% url 'common:common_signin' %}">Sign In</a>
            </div>
        </div>
        

        <div class="container1">
            <div>
            <img src="static/images/bg1.jpg" alt="bg1" height="990px" width="100%">
            </div>
            <div class="content1">
                <h1>Contact Us :</h1><br />
                <img src="static/images/contact.png" alt="contact_image" height="800px" width="90%">
            
            </div>

            <div class="footer">
                <div class="indexfaqs"><a href="{% url 'common:common_faqs' %}">FAQs</a></div>
                <div class="indexcontact"><a href="{% url 'common:common_contact' %}">Contact Us</a></div>
                <div class="privacy">Privacy</div>
                <div class="career">Career</div>
                <div class="legalnotes">Legal notes</div>
                <div class="indexterms">Terms of Use</div>
                
            </div>
        </div>        
    </div>
</body>
</html>

common/templates/common_templates/faqs.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FAQs</title>
    <link rel="stylesheet" href="{% static 'css/faqsstyle.css' %} ">
    
</head>
<body>
    <div class="container" >
        
        <div class="header">
            <div class="logo">
                <a href="{% url 'common:common_index' %}">
                <img src="static/images/logo2.png" height="100%" width="70%" no-repeat >
                </a>
            </div>
            <div class="language">
                <form method="get">
                <select name="language" multiple size="1">
                    <!--size here used to show size of list displayed-->
                    <option selected>English</option>
                    <option>Hindi</option>
                    <option>French</option>
                    <option>German</option>
                    <option>Malayalam</option>
                </select>
                </form>
            </div>
            <div class="signin">
                <a href="{% url 'common:common_signin' %}">Sign In</a>
            </div>
        </div>
        

        <div class="container1">
            <div>
            <img src="static/images/bg1.jpg" alt="bg1" height="2650px" width="100%">
            </div>
            <div class="content1">
                <h1>Frequently Asked Questions :</h1><br />
                <img src="static/images/faq1.png" alt="faq1" height="auto" width="70%">
                <img src="static/images/faq2.png" alt="faq2" height="auto" width="70%">
                <img src="static/images/faq3.png" alt="faq3" height="auto" width="70%">
                <img src="static/images/faq4.png" alt="faq4" height="auto" width="70%">
                <img src="static/images/faq5.png" alt="faq5" height="auto" width="70%">
                <img src="static/images/faq6.png" alt="faq6" height="auto" width="70%">
            
            </div>
            <div class="footer">
                <div class="indexfaqs"><a href="{% url 'common:common_faqs' %}">FAQs</a></div>
                <div class="indexcontact"><a href="{% url 'common:common_contact' %}">Contact Us</a></div>
                <div class="privacy">Privacy</div>
                <div class="career">Career</div>
                <div class="legalnotes">Legal notes</div>
                <div class="indexterms">Terms of Use</div>
                
            </div>
           
                
        </div>
    </div>
</body>
</html>

common/templates/common_templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
    <link rel="stylesheet" href="{% static 'css/customer_homestyle.css' %} ">
    
</head>
<body>
    <div class="container" >
        
        <div class="header">
            <div class="logo">
                <a href="{% url 'common:common_index' %}">
                <img src="static/images/logo2.png" height="100%" width="70%" no-repeat >
                </a>
            </div>
            <div class="language">
                <form method="get">
                <select name="language" multiple size="1">
                    <!--size here used to show size of list displayed-->
                    <option selected>English</option>
                    <option>Hindi</option>
                    <option>French</option>
                    <option>German</option>
                    <option>Malayalam</option>
                </select>
                </form>
            </div>
        </div>
        

        <div class="container1">
            
            <img src="static/images/bg1.jpg" alt="bg1" height="1450px" width="100%">
            
            <div class="content1">
                <div class="movietitle">
                    <label> Movies for you</label>
                </div>

                <div class="movie1">
                    <div><img src="static/images/movie1.png" alt="movie1" width="100%"></div>
                    <div>Kabhi Khushi Kabhie Gham</div>
                </div>

                <div class="movie2">
                    <div><img src="static/images/movie2.png" alt="movie2" width="100%"></div>
                    <div>Ponniyin Selvan-1</div>
                </div>

                <div class="movie3">
                    <div><img src="static/images/movie3.png" alt="movie3" width="100%"></div>
                    <div>Lucifer</div>
                </div>

                <div class="movie4">
                    <div><img src="static/images/movie4.png" alt="movie4" width="100%"></div>
                    <div>Kuch Kuch Hota Hai</div>
                </div>

                <div class="movie5">
                    <div><img src="static/images/movie5.png" alt="movie5" width="100%"></div>
                    <div>Kantara</div>
                </div>

                <div class="movie6">
                    <div><img src="static/images/movie6.png" alt="movie6" width="100%"></div>
                    <div>Harry Potter-5</div>
                </div>

                <div class="movie7">
                    <div><img src="static/images/movie7.png" alt="movie7" width="100%"></div>
                    <div>K.G.F Chapter-2</div>
                </div>

                <div class="movie8">
                    <div><img src="static/images/movie8.png" alt="movie8" width="100%"></div>
                    <div>Kungfu Panda-3</div>
                </div>

                <div class="movie9">
                    <div><img src="static/images/movie9.png" alt="movie9" width="100%"></div>
                    <div>Fast & Furious 9</div>
                </div>

                <div class="movie10">
                    <div><img src="static/images/movie10.png" alt="movie10" width="100%"></div>
                    <div>Tiger zinda hai</div>
                </div>

                <div class="movie11">
                    <div><img src="static/images/movie11.png" alt="movie11" width="100%"></div>
                    <div>Drishyam-2</div>
                </div>

                <div class="movie12">
                    <div><img src="static/images/movie12.png" alt="movie12" width="100%"></div>
                    <div>Chak De! India</div>
                </div>

                <div class="movie13">
                    <div><img src="static/images/movie13.png" alt="movie13" width="100%"></div>
                    <div>San Andreas</div>
                </div>

                <div class="movie14">
                    <div><img src="static/images/movie14.png" alt="movie14" width="100%"></div>
                    <div>Niram</div>
                </div>

                <div class="movie15">
                    <div><img src="static/images/movie15.png" alt="movie15" width="100%"></div>
                    <div>Mission Impossible: Fallout</div>
                </div>

                <div class="movie16">
                    <div><img src="static/images/movie16.png" alt="movie16" width="100%"></div>
                    <div>Interstellar</div>
                </div>

                <div class="moviemore">
                    <div>More Movies </div>
                </div>
                
            </div>
            <div class="footer">
                <div class="indexfaqs"><a href="{% url 'common:common_faqs' %}">FAQs</a></div>
                <div class="indexcontact"><a href="{% url 'common:common_contact' %}">Contact Us</a></div>
                <div class="privacy">Privacy</div>
                <div class="career">Career</div>
                <div class="legalnotes">Legal notes</div>
                <div class="indexterms">Terms of Use</div>
                
            </div>
           
                
        </div>
    </div>
</body>
</html>

common/templates/common_templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <link rel="stylesheet" href="{% static 'css/indexstyle.css' %} ">
    
    
</head>
<body>
    <div class="container" >
        
        <div class="header">
            <div class="logo">
                <a href="{% url 'common:common_index' %}">
                <img src="static/images/logo2.png" height="100%" width="70%" no-repeat >
                </a>
            </div>
            <div class="language">
                <form method="get">
                <select name="language" multiple size="1">
                    <!--size here used to show size of list displayed-->
                    <option selected>English</option>
                    <option>Hindi</option>
                    <option>French</option>
                    <option>German</option>
                    <option>Malayalam</option>
                </select>
                </form>
            </div>
            <div class="signin">
                <a href="{% url 'common:common_signin' %}">Sign In</a>
            </div>
        </div>
        

        <div class="container1">
            <div>
            <img src="static/images/bg1.jpg" alt="bg1" height="700px" width="100%">
            </div>
            <div class="shade">
            </div>
            <div class="index_content1">
                <h1> movies, TV shows and more.<br />
                Watch anywhere. Cancel anytime.<br />
                </h1>
                <h4>Ready to watch? Enter your email to create or restart your membership.
                </h4>
                <form method="get">
                    <div>
                        <div class="index_email" >
                            <input name="email" type="text" placeholder="Enter your Email Address" size="60"/>
                        </div>
                        <div class="index_email_submit">
                        <label><a href="{% url 'common:common_signin' %}">Get Started  ></a></label>
                        </div>

                    </div>
                </form>
                
            </div>
        </div>

        <div class="container2">
            <div class="index_content2">
                Enjoy on your TV.<br /><br />
                Watch on smart TVs, PlayStation, Xbox, <br />
                Chromecast, Apple TV, Blu-ray players and more.
            </div>
            
            <div class="indextvimage">
                <img src="static/images/indextvimage.jpg" alt="indextvimage" height=300px width=480px >  
            </div>

            <div class="indeximage2">
                <img src="static/images/indeximage2.png" alt="indeximage2" height=auto width=auto >
            </div>
        </div>

        <div class="container3">

            <div class="indeximage3">
                <img src="static/images/indeximage3.jpg" alt="indeximage3" height=auto width=auto >
            </div>

            <div class="index_content3">
                <h1>Download your shows <br />
                    to watch offline.<br />
                </h1>
                <h3>
                    Save your favourites easily and always<br />
                    have something to watch.
                </h3>
            </div>
        </div>

        <div class="footer">
            <div class="indexfaqs"><a href="{% url 'common:common_faqs' %}">FAQs</a></div>
            <div class="indexcontact"><a href="{% url 'common:common_contact' %}">Contact Us</a></div>
            <div class="privacy">Privacy</div>
            <div class="career">Career</div>
            <div class="legalnotes">Legal notes</div>
            <div class="indexterms">Terms of Use</div>
            
        </div>   

    </div>
</body>
</html>

common/templates/common_templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link rel="stylesheet" href="{% static 'css/signinstyle.css' %} ">
    
</head>
<body>
    <div class="container" >
        
        <div class="header">
            <div class="logo">
                <a href="{% url 'common:common_index' %}">
                <img src="static/images/logo2.png" height="100%" width="70%" no-repeat >
                </a>
            </div>
            <div class="language">
                <form method="get">
                <select name="language" multiple size="1">
                    <!--size here used to show size of list displayed-->
                    <option selected>English</option>
                    <option>Hindi</option>
                    <option>French</option>
                    <option>German</option>
                    <option>Malayalam</option>
                </select>
                </form>
            </div>
        </div>
        

        <div class="container1">
            <div>
            <img src="static/images/bg1.jpg" alt="bg1" height="700px" width="100%">
            </div>
            <div class="shade">
            </div>
            <div class="content1">
                <h1>Sign In</h1><br />
                <form method="get" action="{% url 'common:customer_home' %}">                    
                    <input name="username" type="text" placeholder="Email or Phone number" size="40"/><br /><br />
                    <input type="password" placeholder="Password" size="40"/><br />
                    <h4><input type="checkbox" />Remember me</h4>
                    <div class="signin">
                    <a href="{% url 'common:customer_home' %}"><h3>Sign In</h3></a>
                    </div>
                    <div class="signin_learnmore">
                    <h3>New to Netflix?<a href="{% url 'common:common_signup' %}"> Sign up </a>now.</h3>
                    <h4>This page is protected by Google reCAPTCHA <br />
                        to ensure you're not a bot. Learn more.</h4>
                    </div>
                    
                </form>
            </div>

            <div class="footer">
                <div class="indexfaqs"><a href="{% url 'common:common_faqs' %}">FAQs</a></div>
                <div class="indexcontact"><a href="{% url 'common:common_contact' %}">Contact Us</a></div>
                <div class="privacy">Privacy</div>
                <div class="career">Career</div>
                <div class="legalnotes">Legal notes</div>
                <div class="indexterms">Terms of Use</div>
                
            </div>
                
        </div>
</body>
</html>

common/templates/common_templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'css/signupstyle.css' %} ">
    
</head>
<body>
    <div class="container" >
        
        <div class="header">
            <div class="logo">
                <a href="{% url 'common:common_index' %}">
                <img src="static/images/logo2.png" height="100%" width="70%" no-repeat >
                </a>
            </div>
            <div class="language">
                <form method="get">
                <select name="language" multiple size="1">
                    <!--size here used to show size of list displayed-->
                    <option selected>English</option>
                    <option>Hindi</option>
                    <option>French</option>
                    <option>German</option>
                    <option>Malayalam</option>
                </select>
                </form>
            </div>
        </div>
        

        <div class="container1">
            <div>
            <img src="static/images/bg1.jpg" alt="bg1" height="700px" width="100%">
            </div>
            <div class="shade">
            </div>
            <div class="content1">
                <h1>Sign Up</h1><br />
                <form method="get" action="{% url 'common:customer_home' %}">                    
                    <input name="username" type="text" placeholder=" Email " size="40"/><br /><br />
                    <input name="username" type="text" placeholder=" Mobile number" size="40"/><br /><br />
                    <input type="password" placeholder="Password" size="40"/><br />
                    <h4><input type="checkbox" />Remember me</h4>
                    <div class="signup">
                    <a href="{% url 'common:customer_home' %}"><h3>Sign Up</h3></a>
                    </div>
                    <div class="signup_learnmore">
                    <h3>Already have an account in Netflix?<br />
                         Then <a href="{% url 'common:common_signin' %}"> Sign In </a>now.</h3>
                    <h4>This page is protected by Google reCAPTCHA <br />
                        to ensure you're not a bot. Learn more.</h4>
                    </div>
                    
                </form>
            </div>

            <div class="footer">
                <div class="indexfaqs"><a href="{% url 'common:common_faqs' %}">FAQs</a></div>
                <div class="indexcontact"><a href="{% url 'common:common_contact' %}">Contact Us</a></div>
                <div class="privacy">Privacy</div>
                <div class="career">Career</div>
                <div class="legalnotes">Legal notes</div>
                <div class="indexterms">Terms of Use</div>
                
            </div>
                
        </div>
</body>
</html>